### ISSUE TITLE
Why failed on test_data?

### ISSUE THREAD

**Issue by qpc001** [KOKIAOKI/3d_bbs#1]
using default param:

```
## 3D-BBS Parameters
min_level_res: 1.0 # [m]
max_level: 6

## Angular Search Range
# 6.28 input is converted to 2*M_PI
min_rpy: [-0.02,-0.02,0.0]
max_rpy: [0.02,0.02,6.28]

################[Optional]################
## Downsample Target Clouds Parameter
valid_tar_vgf: true
tar_leaf_size: 0.1

## Downsample Source Clouds Parameter
valid_src_vgf: true
src_leaf_size: 2.0

cut_src_points: true 
scan_range:
  - 0.0 # min [m]
  - 100 # max [m]
 
## Final align
use_gicp: false
```

![image](https://github.com/KOKIAOKI/3d_bbs/assets/31476516/54ed7f87-df90-4067-9fc7-eb727f1e667c)

**Comment by KOKIAOKI** [comment]
Thank you for testing our code. Are source folder path and target folder path correctly set in yaml? What cuda version do you use?

**Comment by KOKIAOKI** [comment]
Can you change cuda to 12 or higher?
Currently, no other possible causes have been found.

**Comment by KOKIAOKI** [comment]
Thank youf for fixing code.
 for loop did not work correctly due to break.
I approved your PR and merge it into main branch.
