### ISSUE TITLE
wrong rosbag dataset URL

### ISSUE THREAD

**Issue by lucabart97** [KOKIAOKI/3d_bbs#18]
Following this [guide](https://github.com/KOKIAOKI/3d_bbs/blob/main/ros2_test/ros2_test_code.md), the download link of ```ros2_test_data```  (section A.3.2) return to the zip file, not the rosbag.

**Comment by KOKIAOKI** [comment]
@lucabart97 
Thank you for reporting that!
This is the right link.
[ros2_test_data](https://drive.google.com/file/d/1dmyTtV4XRKNn3Z0xUyRNHqmwnaTXvsiz/view?usp=drive_link)

I will fix readme now.
