### ISSUE TITLE
Incorrect acquire pose

### ISSUE THREAD

**Issue by zjg1210** [KOKIAOKI/3d_bbs#28]
Hello brother!
I tested two maps, one of which was constructed by Velodyne as a simulation map. I repositioned at the origin and obtained a pose
0 0 0 0 0
0 1 0 0
0 0 1-1
0 0 0 0 0
This is incorrect on z, the coordinate of z should be 0.
With this question in mind, I tested the real environment map built by Livox,
Repositioning obtained at the origin pose:
0.9998, 0.00059987, 0.0199897, -1
0, 0.99955, -0.0299955, 0
-0.0199987, 0.0299895, 0.99935, -1
0, 0, 0, 1
On x and z, both are -1, which is incorrect. Why?

**Comment by iDonghq** [comment]
> Hello brother! I tested two maps, one of which was constructed by Velodyne as a simulation map. I repositioned at the origin and obtained a pose 0 0 0 0 0 0 1 0 0 0 0 1-1 0 0 0 0 0 This is incorrect on z, the coordinate of z should be 0. With this question in mind, I tested the real environment map built by Livox, Repositioning obtained at the origin pose: 0.9998, 0.00059987, 0.0199897, -1 0, 0.99955, -0.0299955, 0 -0.0199987, 0.0299895, 0.99935, -1 0, 0, 0, 1 On x and z, both are -1, which is incorrect. Why?

I think that 3dbbs finds the best place in a voxel map on different level, its resolution  determines the accurac of relocalization, It can only get a rough location, refine the pose using the series of icp, such as gicp, based on 3dbbs

**Comment by KOKIAOKI** [comment]
Sorry for the delay in activities.
As @iDonghq said, 3d_bbs is coarse global localization method.
It looks like correct behavior.
If you have any questions, please re-open this issue.
Thank you for testing 3D-BBS.
