### ISSUE TITLE
gpu version failed

### ISSUE THREAD

**Issue by yxq953** [KOKIAOKI/3d_bbs#31]
Hello, the compilation passed. My cpu version can be used, but the gpu can't. Is my Driver Version: 535.171.04 related to it? Do I need to lower the driver version?

**Comment by KOKIAOKI** [comment]
Hello! Thank you for visiting 3D-BBS repository.
The driver version seems good. 
Where did the proccess stop?
Could you send me output errors?

**Comment by yxq953** [comment]
Thank you for your reply！
It's stuck here:
yxq@yxq953:~/3dbbs/3d_bbs/test/build$ ./gpu_test ../config/test.yaml 
[YAML] Loading paths...
[YAML] Loading 3D-BBS parameters...
[YAML] Loading angular search range...
[YAML] Loading score threshold percentage...
[YAML] Loading downsample parameters...
[Setting] Loading target pcds...
[Setting] Loading source pcds...
[Setting] Create output folder with date...
[Voxel map] Creating hierarchical voxel map...
[Voxel map] Execution time: 2247.1[msec] 
-------------------------------
[Localize] pcd file name: 1


And my device：
Ubuntu 20.04
eigen 3.3.7
pcl 1.10 
cmake 3.26
cuda 12.1
cudnn 8.9.2

**Comment by KOKIAOKI** [comment]
Thank you for providing the detail information. 
OK. 
Please clone our repositry again with `git clone https://github.com/KOKIAOKI/3d_bbs.git --recursive`

Because eugen3.3.x has a problem in cuda implementation, I recently added the optional newest eigen installation.

**Comment by yxq953** [comment]
Thank you for your answer. I reinstalled eigen3 and it can run successfully！

**Comment by yxq953** [comment]
Thank you for your answer. I reinstalled eigen3 and it can run successfully！
