### ISSUE TITLE
saver error when cloud_map is large

### ISSUE THREAD

**Issue by zuowei1998** [KOKIAOKI/3d_bbs#33]
My "cloud_map.pcd" Occupies 1.7GB of memory(resolutiuon = 0.5m).There is a problem of being killed(core_dump)
![img_v3_02ba_43089c33-b49a-4047-9680-c3dd1792054g](https://github.com/KOKIAOKI/3d_bbs/assets/50592247/966b21da-a5a9-4879-895f-7e44349d2d0f)

How should I implement the saver?

**Comment by KOKIAOKI** [comment]
Hello
Can you try ../../yc_test/test_saver 
without tail /

**Comment by zuowei1998** [comment]
![image](https://github.com/KOKIAOKI/3d_bbs/assets/50592247/58bb00a5-6b34-4f39-95a6-4416f84343b5)
Thank you so much for your response! But unfortunately, the problem persists. Can you please take another look?

**Comment by iDonghq** [comment]
> ![image](https://private-user-images.githubusercontent.com/50592247/334618044-58bb00a5-6b34-4f39-95a6-4416f84343b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDcyMjIsIm5iZiI6MTcxNjk0NjkyMiwicGF0aCI6Ii81MDU5MjI0Ny8zMzQ2MTgwNDQtNThiYjAwYTUtNmIzNC00ZjM5LTk1YTYtNDQxNmY4NDM0M2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAxNDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYzFlYzZiNGQ2NmZmZTEwOTU5NDg5NGZjMTQ3OWY0NzNjZmJkNzI4YWY1MzZkMzI4MzQ3ZjAwNDcwNjBlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_zff7exHDle69wiSsCwZi-puSzQMUZ0a6e0qtBx4MI) Thank you so much for your response! But unfortunately, the problem persists. Can you please take another look?

why cannot downsamle the global map before saving it?  using it for 3D Reconstruction?

**Comment by zuowei1998** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50592247/334618044-58bb00a5-6b34-4f39-95a6-4416f84343b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDcyMjIsIm5iZiI6MTcxNjk0NjkyMiwicGF0aCI6Ii81MDU5MjI0Ny8zMzQ2MTgwNDQtNThiYjAwYTUtNmIzNC00ZjM5LTk1YTYtNDQxNmY4NDM0M2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAxNDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYzFlYzZiNGQ2NmZmZTEwOTU5NDg5NGZjMTQ3OWY0NzNjZmJkNzI4YWY1MzZkMzI4MzQ3ZjAwNDcwNjBlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_zff7exHDle69wiSsCwZi-puSzQMUZ0a6e0qtBx4MI) Thank you so much for your response! But unfortunately, the problem persists. Can you please take another look?
> 
> why cannot downsamle the global map before saving it? using it for 3D Reconstruction?


This cloud_map is the outdoor mapping result. Due to the large scene range, there is still 1.7gb after downsampling to 0.5m resolution.

**Comment by KOKIAOKI** [comment]
Please show me the output when following command
```
./saver ../../yc_test/test_saver 10.0 1
```

We may know whether this problem is due to the size of voxelmap pcd when saver tries to save the minimum voxelmap pcd

**Comment by zuowei1998** [comment]
![image](https://github.com/KOKIAOKI/3d_bbs/assets/50592247/c7b22e1f-1616-4c85-b28a-5c184b076703)
It works when I increase minimum resolution to 10m and keep one level!!!

> Please show me the output when following command
> 
> ```
> ./saver ../../yc_test/test_saver 10.0 1
> ```
> 
> We may know whether this problem is due to the size of voxelmap pcd when saver tries to save the minimum voxelmap pcd

**Comment by KOKIAOKI** [comment]
Let me take a time to reproduce this situation and solve this problem

**Comment by KOKIAOKI** [comment]
I cannot reproduce your situation even though I tried to use some large data.
For example, I successfully saved one of the voxelmap pcd with 2.2GB.

I'm sorry that I haven't have any ideas to solve your problems yet.

**Comment by zuowei1998** [comment]
I think the problem may not only be related to the memory size occupied by the point cloud map, but should be absolutely related to the spatial extent of the real physical world.
