### ISSUE TITLE
occur core_dump in gpu version of calc_score

### ISSUE THREAD

**Issue by zuowei1998** [KOKIAOKI/3d_bbs#34]
![ibX8AxZsov](https://github.com/KOKIAOKI/3d_bbs/assets/50592247/50dc6a45-ac33-4227-8ca0-c3426a33b0ee)
I try to use bbs3d in my own project, but I have a problem with cacl_score. My gpu device is orin_nx. I would really appreciate it if you could reply to this question.

**Comment by KOKIAOKI** [comment]
Hello!  Thank you for using 3D-BBS

I checked it but it's difficult to answer with only this output.
Can you give me more information such as cuda version?
What Eigen version do you use now ?

**Comment by zuowei1998** [comment]
Thanks for your reply. My cuda version = 11.4 and my Eigen version = 3.4.0.

**Comment by KOKIAOKI** [comment]
3D-BBS doesn't support below cuda 12.0
Can you update cuda version in your device?

**Comment by zuowei1998** [comment]
Thanks!!! Maybe I have found the reason. When my last calculation has not been completed and I feed the current frame to bbs at the same time, there may be a core_dump.
