### ISSUE TITLE
Use test data but it always show below the threshold

### ISSUE THREAD

**Issue by j953302** [KOKIAOKI/3d_bbs#35]
I try to use your own test data by ros2.

However, it always show score is below the threshold. No matter how I adjust the parameter to small number.

Below is my ROS2 version and Eigen version:

ROS2 : galactic，20.04 ubuntu
Eigen: 3.7

Best regard.

**Comment by KOKIAOKI** [comment]
Hello! Thank you for trying 3D-BBS.

Could you try this in latest one?
```
git clone https://github.com/KOKIAOKI/3d_bbs.git --recursive
```

Eigen 3.3.4 is cloned as submodule and built inside 3D-BBS
This is because Eigen 3.3.X has some bug in matrix calculation in cuda kernel.

**Comment by j953302** [comment]
> Hello! Thank you for trying 3D-BBS.
> 
> Could you try this in latest one?
> 
> ```
> git clone https://github.com/KOKIAOKI/3d_bbs.git --recursive
> ```
> 
> Eigen 3.3.4 is cloned as submodule and built inside 3D-BBS This is because Eigen 3.3.X has some bug in matrix calculation in cuda kernel.

OK, I will try it. However, I try to change the ros2+gpu_3d_bbs to ros2+cpu_3d_bbs version. And now it work. Thank you.
