### ISSUE TITLE
min_rpy and max_rpy setting and result question

### ISSUE THREAD

**Issue by j953302** [KOKIAOKI/3d_bbs#36]
Hello, I used my own data and use cpu to test 3d_bbs.
And I set the min_rpy and max_rpy in config below:
`min_rpy: [0.0,-2.0,2.0]
max_rpy: [2.5,-1.0,2.2]`

However, the result of [roll, pitch, yaw] is out of my setting. It will output: Roll: 2.48698, Pitch: 0.820313, Yaw: -2.1461e-08.
The result I get it from below:

tf2::Quaternion temp(q.x(), q.y(), q.z(), q.w());
tf2::Quaternion temp(q.x(), q.y(), q.z(), q.w());
tf2::Matrix3x3 m(temp);

double roll, pitch, yaw;
m.getRPY(roll, pitch, yaw);
 
 Is it correct? Thank you. 
 
![2024-06-27 15-02-39 的螢幕擷圖](https://github.com/KOKIAOKI/3d_bbs/assets/48813590/bdea40e6-d81b-4558-807a-2eccf3b80d22)

**Comment by KOKIAOKI** [comment]
Hi! Thank you for trying 3D-BBS.

If I reproduce this problem on my data, I will repot it here.

**Comment by KOKIAOKI** [comment]
I'm sorry it took so long, but I've merged the fix for this bug so I close this issue.
