### ISSUE TITLE
Question about "Conditions for demonstrating 3D-BBS performance on your own data"

### ISSUE THREAD

**Issue by Edwardius** [KOKIAOKI/3d_bbs#40]
It states that the robot with the sensor should be stationary. Does that mean that this method works poorly when the robot is moving? 

It would be a bit odd to me that the proposed method would claim usefulness in robot applications if the robot can't move...

**Comment by KOKIAOKI** [comment]
Sorry for the late reply.

This repository only supports simple IMU gravitational acceleration estimation when the robot is stationary.
However, if the gravitational acceleration can be estimated while the robot is moving (e.g. LiDAR-inertial odometry), 3D-BBS can perform fast global localization.
