### ISSUE TITLE
The processing time variate a lot among multiple runs for the same pair of point cloud

### ISSUE THREAD

**Issue by deliangye** [KOKIAOKI/3d_bbs#41]
Thanks for sharing your project, it is a great job! But I found a problem: for a same pair of point clouds, the processing time variates a lot between multiple runs. Is it nature of algorithm? or the start pose for BBS is random for different runs?

-Deliang

**Comment by KOKIAOKI** [comment]
Thank you for your question.

I see. May I ask a question?
Was source point cloud downsampled? 3D-BBS highly depends on the number of source point cloud. Up to 2000 points is preferable.

When I registered same LiDAR scans, they aligned quickly.
So, I need to know a bit more about the input data.

**Comment by deliangye** [comment]
Yes, I applied voxel grid downsampling, the number of points is less than 2000.  
The algorithm will be failed if the two point clouds is apart from each other far away (is this expected?), so I apply pre-translation to get them closer before running BBS, maybe the pre-translation vector is not deterministic per running (I should change later), which causes this variation of processing time.

**Comment by KOKIAOKI** [comment]
I see.
The distance between point clouds is not relevant to the algorithm.
However, please transform the source points around the origin because source point cloud is rotated around origin.
If the processing time changes from run to run, the value of some variable may be undefined in your code.
