### ISSUE TITLE
How is the comparison of 3d bbs with "MegaParticles: Range-based 6-DoF Monte Carlo Localization with GPU-Accelerated Stein Particle Filter"

### ISSUE THREAD

**Issue by deliangye** [KOKIAOKI/3d_bbs#42]
Hey KokiAoki,

Did you compare 3D BBS to MegaParticles ?  What are the advantages and dis-advantages ?

Thanks!
-Deliang

**Comment by KOKIAOKI** [comment]
No. I haven't evaluated MegaParticles unfortunately.

My thoughts are below, but in reality, it's a comparison between One-shot localization and Monte Carlo localization in the context of initial pose estimation.

- 3D-BBS Advantages
  - High GPU usage is instantaneous. Easy to combine with other applications.
  - Performance is almost the same for the map range of the paper, but performance may differ for larger maps.

- Megaparticles Advantages
  - MegaParticles can quickly find a complete 6-DOF pose.
  - MegaParticles can provide multiple pose candidates even in a feature-less environment.
