### ISSUE TITLE
Taking a long time to localize, asking for parameters setting suggestion

### ISSUE THREAD

**Issue by BobH62** [KOKIAOKI/3d_bbs#43]
Thanks for sharing your project. I am also doing research on global registration and use 3d bbs as a baseline. As I applied 3dbbs to my datasets, it takes about 2 hours to localize a pointcloud. Although I know my target map is really big(about 200m * 100m), I am not sure if it's the parameters setting issue that leads to this long period of time. 
I would be appreciative if you could give me your email, and I could share with you some samples of my datasets (including the source pointcloud and the target pointcloud) to test, or you could contact me via: hhuangce@connect.ust.hk

![Screenshot from 2024-08-27 16-15-55](https://github.com/user-attachments/assets/dd29eb2f-01b7-4005-a9f5-4fa4df2cb63a)
![Screenshot from 2024-08-27 16-16-21](https://github.com/user-attachments/assets/1062612e-4f0c-4fbc-a566-43ca435d9f4f)

**Comment by KOKIAOKI** [comment]
Thank you. Let me contact you via email.

**Comment by KOKIAOKI** [comment]
Hello. Have you received my email message a few days ago?

**Comment by KOKIAOKI** [comment]
@CLboyrobot
Sorry for the late reply.
-DCMAKE_BUILD_TYPE=Release was not added in this case.
When building, please run cmake .. -DCMAKE_BUILD_TYPE=Release
