### ISSUE TITLE
Some questions about rotation constraint of 3D-BBS

### ISSUE THREAD

**Issue by hwan0806** [KOKIAOKI/3d_bbs#44]
Hi Aoki!

It’s been a while since we met at ICRA '24 with @U-AMC. 
The academic discussions we had were really interesting and helpful.

I've been testing your algorithm lately, and it performs exceptionally well in terms of scalability and generality. 
Honestly, I think the 3D-BBS paper is the GOAT for LiDAR localization, haha. 
However, I encountered a few issues during my testing, and I wanted to ask for your advice.

1. [ translational constraint test ]
I slightly modified your test code from searching the global map to searching local area using prior pose information as similar as #26 did. As expected, the prior pose data significantly improved localization performance. The only modification I made was restricting the translational search area by `set_trans_search_range()`. This works well.

2. [ rotational constraint test ]
Next, I added constraints on rotation (min_rpy, max_rpy) set as (gt_yaw - theta, gt_yaw + theta) and conducted further testing. However, I noticed a significant drop in localization performance. In most of the failed cases, it results in a "score below the threshold," and I’m not sure why. 
I think this issue might be related to what’s mentioned in #36.
The strangest part is that when I set theta as π (which makes the rotational range 2π), it works perfectly. 
But in cases where the rotational range is smaller than 2π, the performance drops significantly!

What i modified is,
- set `(min_rpy, max_rpy )` as `(gt_yaw - theta, gt_yaw + theta)`
- set `ang_info_vec[i].min_rpy.z() = min_rpy_.z()` in `calc_angular_info()` for correct `create_matrix()`.

Is there a part of the code that sets the rotation range to 2π internally? Or could I be missing something else?

Looking forward to hearing your thoughts!

Best regards,
Gilhwan

**Comment by KOKIAOKI** [comment]
I just looked at the source code and noticed a problem. When the search range of the rotational component is a few rads, at high levels it is below ori_res and 0 rad is entered. Therefore, if the search range of the rotational component does not include 0, matching will continue with an incorrect pose.

To solve this problem, I need to fix [this](https://github.com/KOKIAOKI/3d_bbs/blob/91c6d4dc038b8eda6bc082122f86207fd8a6d7e5/bbs3d/src/cpu_bbs3d/bbs3d.cpp#L78C5-L78C81) as following:
```
rpy_res_temp.x() = ori_res <= (max_rpy_.x() - min_rpy_.x()) ? ori_res : min_rpy_.x() + (max_rpy_.x() - min_rpy_.x())/2 ;
```

I need to fix the algorithm of the function including this line, so I'll let you know when I get it working properly!

**Comment by hwan0806** [comment]
Thanks, Aoki, for your kind explanation and thoughtful response.
I really appreciate you taking the time to address this issue, especially with your busy schedule!

I've reviewed the code you mentioned, and I believe it is already reasonable and the problem i met is not due to any mistake on your part. Since `ori_res` is calculated based on the maximum scan distance, it tends to be small. Additionally, I set the yaw_threshold quite roughly (between 0.25π and 0.5π). So in my cases, the issue you mentioned is unlikely to occur.

I also checked the `num_division` in `calc_angular_info()` across all voxel levels, and I confirmed that there are no instances where the value becomes zero; everything branches correctly.

These facts make debugging the issue I encountered more challenging :disappointed_relieved: 
Have you been able to reproduce this problem? 
If not, I can run the same experiment using an open dataset and share the data with you :)

**Comment by KOKIAOKI** [comment]
Thank you for debugging in detail.
I see. I haven't reproduced that case maybe, so cloud you send me some example data with open dataset? It's very helpful for debugging!

**Comment by hwan0806** [comment]
I apologize for the delayed response. I had a very busy week. 
May I ask the best way to get in touch with you? 
Would it be possible to contact you via this email address: 180447001@ccalumni.meijo-u.ac.jp?

**Comment by KOKIAOKI** [comment]
I would be happy if you could respond when you have time.
Yes.  [180447001@ccalumni.meijo-u.ac.jp](mailto:180447001@ccalumni.meijo-u.ac.jp) is fine!

**Comment by hwan0806** [comment]
I have reached out via email. 
Let’s continue discussing any further developments there. 
I’ll close this issue for now.
