### ISSUE TITLE
Why do I get no results in gpu mode when I use your test_data data (using./gpu_test), and the calculated scores are all zeros

### ISSUE THREAD

**Issue by WillCode1** [KOKIAOKI/3d_bbs#47]
Why do I get no results in gpu mode when I use your test_data data (using./gpu_test), and the calculated scores are all zeros.
![Screenshot from 2024-11-23 15-12-01](https://github.com/user-attachments/assets/5dd15345-f2bd-4a4f-9d6e-611d27162053)

**Comment by KOKIAOKI** [comment]
What OS and Eigen version do you use?
If ubuntu 20 and Eigen 3.3.X, did you clone with --recursive?
